name: qir-book
channels:
  - conda-forge
  - microsoft
  - defaults
dependencies:
  - python=3.9
  - matplotlib==3.6.2
  - numpy==1.23.4
  - pip==22.3
  - dotnet-sdk>=6.0
  # Required by .NET Interactive.
  - dotnet-aspnetcore>=6.0
  - notebook==6.5.2
  - llvm-tools=13
  - iqsharp==0.27.238334
  - qsharp==0.27.238334
  #- pyquil==1.9.0
  - autopep8==1.6.0
  - click==7.1.2
  - lit==12.0.1
  - toml==0.10.2
  - pandas==1.5.0
  - ipykernel==6.15
  - pytest==7.2.0
  # - graphviz==2.50
  - pip:
    - sphinx-design==0.1.0
    - jupyter-book==0.13.1
    - lit==12.0.1
    #- git+https://github.com/crazy4pi314/qutip-qip@crazy4pi314/record-output#egg=qutip_qip
    - qutip
    #- pyqir==0.6.2
    #- azure-quantum==0.27.238334
    - qiskit_qir
